BEGIN;
    CREATE TYPE loan_status_enum AS ENUM
    (
        'proposed',
        'approved',
        'interested',
        'disbursed'
    );
    
    CREATE TABLE IF NOT EXISTS loan_logs
    (
        id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        guid UUID NOT NULL DEFAULT uuid_generate_v1(),
        loan_id int NOT NULL,
        status loan_status_enum DEFAULT 'proposed',
        employee_id int,

        created_at timestamp with time zone DEFAULT now()
    );

    CREATE INDEX idx_loan_logs_guid ON loan_logs(guid);
    CREATE INDEX idx_loan_logs_status ON loan_logs(status);

    ALTER TABLE loan_logs
        ADD CONSTRAINT fk_loan_logs_loan_id
        FOREIGN KEY (loan_id)
        REFERENCES loans(id)
        ON DELETE RESTRICT
        ON UPDATE CASCADE;

    ALTER TABLE loan_logs
        ADD CONSTRAINT fk_loan_logs_employee_id
        FOREIGN KEY (employee_id)
        REFERENCES employees(id)
        ON DELETE RESTRICT
        ON UPDATE CASCADE;
COMMIT;