BEGIN;
    CREATE TABLE IF NOT EXISTS loans
    (
        id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        guid UUID NOT NULL DEFAULT uuid_generate_v1(),
        borrower_id int NOT NULL,
        principal_amount bigint NOT NULL,
        rate numeric(6,4) NOT NULL,
        return_of_investment bigint NOT NULL,
        agreement_letter_link text,

        created_at timestamp with time zone DEFAULT now(),
        updated_at timestamp with time zone DEFAULT now(),
        deleted_at timestamp with time zone
    );

    CREATE INDEX idx_loan_guid ON loans(guid);

    ALTER TABLE loans
        ADD CONSTRAINT fk_loans_borrower_id
        FOREIGN KEY (borrower_id)
        REFERENCES borrowers(id)
        ON DELETE RESTRICT
        ON UPDATE CASCADE;
COMMIT;