BEGIN;
    CREATE TABLE IF NOT EXISTS lender_loans
    (
        id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        guid UUID NOT NULL DEFAULT uuid_generate_v1(),
        lender_id int NOT NULL,
        loan_id int NOT NULL,
        invested_amount bigint NOT NULL,

        created_at timestamp with time zone DEFAULT now(),
        updated_at timestamp with time zone DEFAULT now(),
        deleted_at timestamp with time zone
    );

    CREATE INDEX idx_lender_loan_guid ON lender_loans(guid);

     ALTER TABLE lender_loans
        ADD CONSTRAINT fk_lender_loans_loan_id
        FOREIGN KEY (loan_id)
        REFERENCES loans(id)
        ON DELETE RESTRICT
        ON UPDATE CASCADE;

    ALTER TABLE lender_loans
        ADD CONSTRAINT fk_lender_loans_lender_id
        FOREIGN KEY (lender_id)
        REFERENCES lenders(id)
        ON DELETE RESTRICT
        ON UPDATE CASCADE;
COMMIT;