BEGIN;
    CREATE TABLE IF NOT EXISTS loans
    (
        id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        borrower_id int NOT NULL,
        principal_amount bigint,
        rate numeric(6,4),
        return_of_investment bigint,
        agreement_letter_link text,

        created_at timestamp with time zone NOT NULL DEFAULT now(),
        updated_at timestamp with time zone NOT NULL DEFAULT now(),
        deleted_at timestamp with time zone
    );

    ALTER TABLE loans
        ADD CONSTRAINT fk_loans_borrower_id
        FOREIGN KEY (borrower_id)
        REFERENCES borrowers(id)
        ON DELETE RESTRICT
        ON UPDATE CASCADE;
COMMIT;