BEGIN;
    CREATE TABLE IF NOT EXISTS borrowers
    (
        id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        first_name text,
        last_name text,

        created_at timestamp with time zone NOT NULL DEFAULT now(),
        updated_at timestamp with time zone NOT NULL DEFAULT now(),
        deleted_at timestamp with time zone
    );

    INSERT INTO borrowers (first_name, last_name) VALUES ('John', 'Doe');
COMMIT;
